import { NextRequest, NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/server/auth";
import type { TeamSummaryResponse } from "@/lib/types";
import {
  consumeRateLimitToken,
  rateLimitKeyForRequest,
} from "@/lib/server/rate-limit";

const MAX_FIELD = 4000;
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX_REQUESTS = 15;

function jsonTooManyRequests(retryAfterSeconds: number): NextResponse {
  const res = NextResponse.json(
    {
      error: "Too many summary requests. Please wait a minute.",
      code: "rate_limited",
      retryAfterSeconds,
    },
    { status: 429 },
  );
  res.headers.set("Retry-After", String(retryAfterSeconds));
  return res;
}

export async function POST(req: NextRequest) {
  const user = await getUserFromRequest(req);
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const rlKey = rateLimitKeyForRequest({
    namespace: "team_summary",
    userId: user.id,
    req,
  });
  const rl = consumeRateLimitToken({
    key: rlKey,
    windowMs: RATE_LIMIT_WINDOW_MS,
    maxRequests: RATE_LIMIT_MAX_REQUESTS,
  });
  if (!rl.allowed) {
    return jsonTooManyRequests(rl.retryAfterSeconds);
  }

  const body = await req.json().catch(() => ({}));
  const rubric =
    typeof body.rubric === "string" ? body.rubric.trim().slice(0, MAX_FIELD) : "";
  const notes =
    typeof body.notes === "string" ? body.notes.trim().slice(0, MAX_FIELD) : "";
  if (!rubric || !notes) {
    return NextResponse.json({ error: "Rubric and notes are required." }, { status: 400 });
  }

  const summary = `## Panel summary (draft)

### Rubric alignment
- ${rubric.split(/\n+/).filter(Boolean).slice(0, 5).join("\n- ") || "(no rubric lines)"}

### Candidate / loop notes
${notes.slice(0, 1200)}${notes.length > 1200 ? "…" : ""}

### Recommended next steps
1. Align on pass/fail signals for the highest-weight rubric rows.
2. Capture one concrete example per competency (what good looks like).
3. Debrief within 24h while signals are fresh.

_Generated by InfinityHire Copilot — edit before sharing._`;

  const payload: TeamSummaryResponse = { summary, source: "fallback" };
  return NextResponse.json(payload);
}
