import { NextRequest, NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/server/auth";
import type { CompanyMode, Role, SessionDebrief, ShareReportResponse } from "@/lib/types";
import {
  consumeRateLimitToken,
  rateLimitKeyForRequest,
} from "@/lib/server/rate-limit";
import { trackEvent } from "@/lib/server/event-store";

const VALID_ROLES = new Set<string>([
  "ml-engineer",
  "data-scientist",
  "ai-architect",
  "backend",
  "fullstack",
  "product",
]);

const VALID_COMPANY_MODES = new Set<CompanyMode>([
  "generic",
  "google",
  "amazon",
  "razorpay",
  "atlassian",
  "flipkart",
]);

const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX_REQUESTS = 15;

function jsonTooManyRequests(retryAfterSeconds: number): NextResponse {
  const res = NextResponse.json(
    {
      error: "Too many share report requests. Please wait a minute.",
      code: "rate_limited",
      retryAfterSeconds,
    },
    { status: 429 },
  );
  res.headers.set("Retry-After", String(retryAfterSeconds));
  return res;
}

function isSessionDebrief(v: unknown): v is SessionDebrief {
  if (!v || typeof v !== "object") return false;
  const o = v as Record<string, unknown>;
  return (
    typeof o.overallScore === "number" &&
    Array.isArray(o.strengths) &&
    Array.isArray(o.improvementAreas) &&
    Array.isArray(o.nextPracticeQuestions) &&
    typeof o.conciseCoachNote === "string"
  );
}

function buildReportText(input: {
  debrief: SessionDebrief;
  role: Role;
  companyMode: CompanyMode;
  highlights: string[];
}): string {
  const { debrief, role, companyMode, highlights } = input;
  const lines: string[] = [
    "InfinityHire Copilot — interview session report",
    `Role: ${role} · Interview bar: ${companyMode}`,
    "",
    `Overall score: ${debrief.overallScore}/100`,
    "",
    "Strengths:",
    ...debrief.strengths.map((s) => `- ${s}`),
    "",
    "Improvement areas:",
    ...debrief.improvementAreas.map((s) => `- ${s}`),
    "",
    "Next practice questions:",
    ...debrief.nextPracticeQuestions.map((s, i) => `${i + 1}. ${s}`),
    "",
    "Coach note:",
    debrief.conciseCoachNote,
  ];
  if (highlights.length > 0) {
    lines.push("", "Session highlights:", ...highlights.map((h) => `- ${h}`));
  }
  lines.push("", "— Generated by InfinityHire Copilot");
  return lines.join("\n");
}

export async function POST(req: NextRequest) {
  const user = await getUserFromRequest(req);
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const rlKey = rateLimitKeyForRequest({
    namespace: "session_share_report",
    userId: user.id,
    req,
  });
  const rl = consumeRateLimitToken({
    key: rlKey,
    windowMs: RATE_LIMIT_WINDOW_MS,
    maxRequests: RATE_LIMIT_MAX_REQUESTS,
  });
  if (!rl.allowed) {
    return jsonTooManyRequests(rl.retryAfterSeconds);
  }

  const body = await req.json().catch(() => ({}));
  const debriefRaw = body.debrief;
  if (!isSessionDebrief(debriefRaw)) {
    return NextResponse.json({ error: "Valid debrief payload is required." }, { status: 400 });
  }
  const debrief = debriefRaw;

  const roleRaw = typeof body.role === "string" ? body.role : "";
  if (!VALID_ROLES.has(roleRaw)) {
    return NextResponse.json({ error: "Invalid role selected." }, { status: 400 });
  }
  const role = roleRaw as Role;

  let companyMode: CompanyMode = "generic";
  const companyRaw = body.companyMode;
  if (companyRaw !== undefined && companyRaw !== null && companyRaw !== "") {
    if (typeof companyRaw !== "string" || !VALID_COMPANY_MODES.has(companyRaw as CompanyMode)) {
      return NextResponse.json({ error: "Invalid company mode." }, { status: 400 });
    }
    companyMode = companyRaw as CompanyMode;
  }

  const highlights: string[] = [];
  const rawHi = body.highlights;
  if (Array.isArray(rawHi)) {
    for (const item of rawHi) {
      if (typeof item === "string" && item.trim()) {
        highlights.push(item.trim().slice(0, 400));
        if (highlights.length >= 12) break;
      }
    }
  }

  const reportText = buildReportText({ debrief, role, companyMode, highlights });

  trackEvent(user.id, "share_report_generated", { role, companyMode }).catch(() => {});

  const payload: ShareReportResponse = { reportText };
  return NextResponse.json(payload);
}
